apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-operators
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - path: resources/operators
      repoURL: 'https://github.com/pcastelo/prueba-operators.git'
      targetRevision: HEAD
      helm:
        valueFiles:
          - values.yaml
    - path: resources/
      repoURL: 'https://github.com/pcastelo/prueba-operators.git'
      targetRevision: HEAD
      ref: myRepo  

  syncPolicy:
    automated:
      selfHeal: true
