{{- range .Values.subscriptions }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ .name }}-policy
  namespace: policies
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/standards: ""
    policy.open-cluster-management.io/controls: ""
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ .name }}-cp
        spec:
          remediationAction: enforce
          severity: medium
          object-templates:
            {{- if ne .namespace "openshift-operators" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: {{ .namespace }}
            {{- end }}
            {{- if ne .namespace "openshift-operators" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha2
                kind: OperatorGroup
                metadata:
                  name: {{ .name }}
                  namespace: {{ .namespace }}
                spec: {}
            {{- end }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: {{ .name }}
                  namespace: {{ .namespace }}
                spec:
                  name: {{ .name }}
                  channel: {{ .channel }}
                  installPlanApproval: Automatic
                  source: "redhat-operators"
                  sourceNamespace: "openshift-marketplace" 
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ .name }}-policy-placement
  namespace: policies
placementRef:
  name: openshift-gitops
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ .name }}-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy
{{ end }}